名称：Android CI

在……之上：
推：
分支机构：["主要"]temurin分布：]
pull_request：
分支机构：["主要"]["主要"]

作业：
建立：

run-on:ubuntu-latest

步骤：
-使用：操作/结帐@v4
-名称：设置JDK11
用法：操作/setup-java@v4
和……一起：
java版本："11"
分布：'铁木林''temurin''
缓存：渐变

-名称：授予gradlew执行权限
运行：chmod+x gradlew
-名称：使用Gradle生成
运行：./gradlew生成
